export const BRANCHES = [
  "Bachelor of Architecture (B.Arch)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Design (B.Des)",
  "BBA-IEV (Innovation, Entrepreneurship, and Venture Development)",
  "Biotechnology",
  "Civil Engineering",
  "COE (Computer Engineering)",
  "Computer Science Engineering",
  "Computer Science Engineering (Artificial Intelligence)",
  "Computer Science Engineering (Big Data Analytics)",
  "Computer Science Engineering (Data Science)",
  "Computer Science Engineering (IoT)",
  "Electrical Engineering",
  "Electronics and Communication Engineering",
  "Electronics and Communication Engineering (ECAM)",
  "Electronics Engineering (VLSI Design)",
  "Geoinformatics (GI)",
  "Information Technology",
  "Information Technology (Network Security)",
  "Instrumentation and Control Engineering",
  "Mathematics and Computing (MAC)",
  "Mechanical Engineering",
  "Mechanical Engineering - Electric Vehicles (MEEV)",
  "MPAE (Manufacturing Processes and Automation Engineering)",
  "M.Tech (Biochemical Engineering)",
  "M.Tech (Bioinformatics)",
  "M.Tech (CAD/CAM)",
  "M.Tech (Communication and Networking)",
  "M.Tech (Computer Science)",
  "M.Tech (Electrical Engineering)",
  "M.Tech (Embedded System & VLSI)",
  "M.Tech (Engineering Management)",
  "M.Tech (Industrial Electronics)",
  "M.Tech (Manufacturing Process & Automation)",
  "M.Tech (Mechatronics)",
  "M.Tech (Nano Technology)",
  "M.Tech (Process Control)",
  "M.Tech (Production Engineering)",
  "M.Tech (Signal Processing)",
] as const;

export const CAMPUSES = ["Main Campus", "East Campus", "West Campus"] as const;

export type Branch = (typeof BRANCHES)[number];
export type Campus = (typeof CAMPUSES)[number];